# Generated by Django 4.2 on 2024-10-28 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id пользователя')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Почта пользователя')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль пользователя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания пользователя')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='id сообщения')),
                ('subject', models.CharField(max_length=255, verbose_name='Отправитель/получатель')),
                ('sent_date', models.DateTimeField(verbose_name='Дата отправки сообщения')),
                ('received_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения сообщения')),
                ('message_subject', models.TextField(verbose_name='Тема сообщения')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('attachments', models.JSONField(blank=True, verbose_name='Список файлов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
